### ISSUE TITLE
Allow adding of components in runtime

### ISSUE THREAD

**Issue by benjick** [kodbruket/vsf-storyblok-sync#16]
Currently the render process of the bloks is not inside the package, it's found inside the `theme`-folder and to use this package you have to copy/paste a lot of basic files into your theme, this is not ideal

We need to allow the adding of components in runtime (working with ssr) so we can bundle default components like `debug`, `grid`, `page` lowering the threshold of getting started with this package.

We also need to allow overwriting components (behind a force flag maybe to avoid collisions) so users can supply their own `grid` for example

**Comment by zimme** [comment]
Can't we just export the components/mixins from `@kodbruket/vsf-storyblok-module`?

**Comment by benjick** [comment]
Fixed in #38
